# 所有时间单位均为毫秒

token:
  cd: 30000 # 每个点绘图的冷却时间
  interval: 1000 # 空 token 时的重试间隔

pb:
  width: 1000 # 画板宽度
  height: 600 # 画板高度
  refresh: 180000 # 画板整体刷新间隔

painter:
  random: true # 是否启用随机顺序绘图
  retry: 1000 # 如果已经到时间但是服务器返回正在冷却，那么再等待多久

socket:
  # http: "http://pbdm1.uwuwu.us.kg:22767"
  # http: "https://pb.cyezoi.com"
  http: "https://api.paintboard.ayakacraft.com:32767"

  # ws: "ws://pbdm1.uwuwu.us.kg:22767/api/paintboard/ws"
  # ws: "wss://pb.cyezoi.com/api/paintboard/ws"
  ws: "wss://api.paintboard.ayakacraft.com:32767/api/paintboard/ws"
  
  batch: true # 是否启用粘包
  retry: 1000 # 重连间隔

server:
  port: 3000 # 本地服务器端口
  bodyLimit: 30 # 上传数据大小限制 
  password: "NOIP2024rp++" # 网页管理员密码
  session: 3600000 # session 过期时间
  referer: # 允许的 referer
    - "localhost:3000"
    - "pb.langningchen.com"
